const mongoose= require('mongoose');

const ProfileSchema=new mongoose.Schema({
     _id:{
        type:String,
        required:true,
    },name:{
        type:String,
        required:true,
        min:4,
        max:255
    },
    dob:{
        type:Number,
        required:true,
    },
    bio:{
        type:String,
        required:true,
        min:20,
        max:500
    },
    gender:{
        type:String,
        enum:['MALE','FEMALE','OTHER'],
        required:true
    },
    interestedIn:{
        type:String,
        enum:['MALE','FEMALE','OTHER'],
        required:true
    },
    jobTitle:{
        type:String,
        default:"N/A"
    },
    company:{
        type:String,
        default:"N/A"
    },
    school:{
        type:String,
        default:"N/A"
    },
    verified:{
        type:Boolean,
        default:false
    },
    nickName:{
        type:String,
        required:true,
        min:4,
        max:255
    },
    displayPicture:{
        type:String
    },
    portfolio:{
        type:Array,
        default:[]
    },
    interests:{
        type:Array,
        default:[]
    },
      notifToken:{
        type:String,
        required:true,
    },
    deviceId:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true
    },
    district:{
        type:String,
        required:true,
    },
    state:{
        type:String,
        required:true
    },
    latitude:{
        type:String,
        required:true,
    },
    longitude:{
        type:String,
        required:true
    },
    country:{
        type:String,
        required:true,
    },
    authMethod:{
        type:String,
        enum:["GOOGLE,FB,PHONE"],
        required:true
    },
})

module.exports = mongoose.model('Profile',ProfileSchema,'user_profiles')